### PR TITLE
UMD export

### LINKED ISSUE #4: Feature request: UMD export
Hi! The library is great but in has a disadvantage: it doesn't support Common JS import (i.e. `const workly = require('workly');`).

I understand that NodeJS doesn't support web workers but CJS is used in other cases, e.g. in Electron (which supports both browser and NodeJS APIs) or bundling JS files using Rollup.

I thing exporting the library in the UMD format is a great solution.

### PR DESCRIPTION
**Pull request by FinesseRus**
I've:

* Changed the script export format to [UMD](https://github.com/umdjs/umd). This is an all-in-once format: global variable, AMD, CommonJS.
* Changed the main script to `dist/workly.js` in `package.json` because CommonJS doesn't support `export`. For those who does I've added the `jsnext:main` parameter. 
* Fixed the minification command (it appended the script instead of overwriting).

All the changes helps to use the library in more environments, e.g. Electron, Browserify, Rollup, Webpack, AMD. Resolves #4.

A note about the size in the readme. I inputed the minified code to [a special service](http://www.txtwizard.net/compression) and it said me that the gzipped version size is 1126 bytes which is 1.099kB. And I've made the `b` letter capital because `b` is bit and `B` is bite (I can change it back if you want).

Could you please bump a version and publish it? It is not a breaking change but can cause issues for those who use AMD so the version `1.1.0` should be ok.

### CODE REVIEW

**Comment by pshihn** [comment]
Thanks for this. Let me try it out and see if I can tweak it to create multiple builds the way I want it. I'll pull your PR into that. Will probably get to it tomorrow.

**Comment by FinesseRus** [comment]
@pshihn 

> I'd want to create multiple build outputs. workly.js, workly.umd.js, etc.

For what? UMD is suitable for all the environments. Making a single UMD build is a common standard. For example, jQuery does it: there are no separate format files in [the `dist` directory](https://www.jsdelivr.com/package/npm/jquery?path=dist) and the `package.json` `main` property [points](https://github.com/jquery/jquery/blob/master/package.json#L6) to the UMD file in the `dist` directory. 

> I'll pull your PR into that. Will probably get to it tomorrow.

Tell me if you want to change something in the pull request.

**Comment by pshihn** [comment]
I know UMD is common. I think this is fine. I just have this irrational urge to make the build smaller for this project. 0.2kB smaller without UMD. Not a very good reason, I know :)

**Comment by pshihn** [comment]
@FinesseRus  Thanks for doing this, btw.

**Pull request merged**
